user/models.py
from mongoengine import signals

from application import db
from utilities.common import utc_now_ts as now

class User(db.Document):
    username = db.StringField(db_field="u", required=True, unique=True) 
    # db_field is used incase of high traffic app. Reference to username as u, to save lot of characters.
    password = db.StringField(db_field="p", required=True)
    email = db.StringField(db_field="e", required=True, unique=True)
    firstname = db.StringField(db_field='fn', required=True, max_length=50)
    lastname = db.StringField(db_field='ln', required=True, max_length=50)
    created = db.IntField(db_field='c', default=now())
    bio = db.StringField(db_field='b', max_length=160)

    @classmethod # buildin mongoengine method , its always called before object is writen to db
    def pre_save(cls, sender, document, **kwarge):
        document.username = document.username.lower()
        document.email = document.email.lower()

    meta = {                                          # Creating index to make seach quicker
        'indexes': ['username', 'email', '-created']  # -created : Sort Order should be reversed! Most recent created first
    }

signals.pre_save.connect(User.pre_save, sender=User)

user/forms.py
import re
from flask_wtf import Form
from wtforms import validators, StringField, PasswordField
from wtforms.fields.html5 import EmailField
from wtforms.validators import ValidationError
from wtforms.widgets import TextArea

from user.models import User

class BaseUserForm(Form):
    firstname = StringField('First Name', [validators.DataRequired()])
    lastname = StringField('Last Name', [validators.DataRequired()])
    email = EmailField('Email address', [
        validators.DataRequired(),
        validators.Email()
        ]
    )
    username = StringField('Username', [
        validators.DataRequired(),
        validators.length(min=4, max=25)
        ])
    bio = StringField('Bio',
        widget=TextArea(),
        validators=[validators.Length(max=160)])

class RegisterForm(BaseUserForm):
    password = PasswordField('New Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Passwords must match'),
        validators.length(min=4, max=80)
        ])
    confirm = PasswordField('Repeat Password')

    def validate_username(form, field):
        if User.objects.filter(username=field.data).first():
            raise ValidationError("Username already exists")
        if not re.match("^[a-zA-Z0-9_-]{4,25}$", field.data):
            raise ValidationError("Invalid Username")

    def validate_email(form, field):
        if User.objects.filter(email=field.data).first():
                raise ValidationError("Email is already in use")

class LoginForm(Form):
    username = StringField('Username', [
        validators.DataRequired(),
        validators.length(min=4, max=25)
        ])
    password = PasswordField('Password', [
        validators.DataRequired(),
        validators.length(min=4, max=80)
        ])

class EditForm(BaseUserForm):
    pass

user/views.py
from flask import Blueprint, render_template, redirect, session, request, url_for, abort
import bcrypt
from user.models import User
from user.forms import RegisterForm, LoginForm, EditForm

user_app = Blueprint('user_app', __name__) # To call this module

@user_app.route('/register', methods=('GET', 'POST'))
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data.encode('utf-8'), salt)
        user = User(
            username=form.username.data,
            password=hashed_password,
            email=form.email.data,
            firstname=form.firstname.data,
            lastname=form.lastname.data
            )
        user.save()
        return "User registered"

    return render_template('user/register.html', form=form)

@user_app.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    error = None

    if request.method == 'GET' and request.args.get('next'):
        session['next'] = request.args.get('next')

    if form.validate_on_submit():
        user = User.objects.filter(username=form.username.data).first()
        if user:
            user_password = user.password.encode('utf-8')
            if bcrypt.hashpw(form.password.data.encode('utf-8'), user_password) == user_password:
                session['username'] = form.username.data
                if 'next' in session:
                    next = session.get('next')
                    session.pop('next')
                    return redirect(next)
                else:
                    return 'User Logged In'
            else:
                user = None
        if not user:
            error = 'Incorrect Credentials'
    return render_template('user/login.html', form=form, error=error)

@user_app.route('/logout', methods=('GET', 'POST'))
def logout():
    session.pop('username')
    return redirect(url_for('user_app.login'))

@user_app.route('/<username>', methods=('GET', 'POST'))
def profile(username):
    edit_profile = False
    user = User.objects.filter(username=username).first()
    if session.get('username') and user.username == session.get('username'):
        edit_profile = True
    if user:
        return render_template('user/profile.html', user=user, edit_profile=edit_profile)
    else:
        abort(404)

@user_app.route('/edit', methods=('GET', 'POST'))
def edit():
    error = None
    message = None
    user = User.objects.filter(username=session.get('username')).first()
    if user:
        form = EditForm(obj=user)
        if form.validate_on_submit():
            if user.username != form.username.data:
                if User.objects.filter(username=form.username.data.lower()).first():
                    error = "Username already exists"
                else:
                    session['username'] = form.username.data.lower()
                    form.username.data = form.username.data.lower()
            if user.email != form.email.data:
                if User.objects.filter(email=form.email.data.lower()).first():
                    error = "Email already exists"
                else:
                    form.email.data = form.email.data.lower()
            if not error:
                form.populate_obj(user)
                user.save()
                message = "Profile updated"
        return render_template("user/edit.html", form=form, error=error, message=message)
    else:
        abort(404)

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
  {{ field.label }}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class="text-danger">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
</div>
{% endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

    {% block header %}{% endblock %}
</head>

<body>

    <div class="container">

        {% block content %}{% endblock %}

        <div class="col-md-offset-3 col-md-6">
            <hr />
            <footer>
                &copy; copyright 2020 flaskbook
            </footer>
        </div>

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.1.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>

</html>

templates/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">
                <img alt="flaskbook logo" width="82" height="20"
                    src="{{ url_for('static', filename='assets/flaskbook-logo-sm.png') }}">
            </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if session.username %}
                <li>
                    <p class="navbar-text">Welcome, <a href="#" class="navbar-link">{{ session.username }}</a></p>
                </li>
                <li>
                    <a href="{{ url_for('user_app.logout') }}" class="navbar-link">Logout</a></p>
                </li>
                {% else %}
                <li>
                    <a href="{{ url_for('user_app.login') }}" class="navbar-link">Login</a></p>
                </li>
                <li>
                    <a href="{{ url_for('user_app.register') }}" class="navbar-link">Register</a></p>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/user/edit.html
{% extends "base.html" %}

{% block title %}Edit profile{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

    <div class="col-md-offset-3 col-md-6">

        <h3>Edit Profile</h3>

        {% if error %}
        <div class="alert alert-danger" role="alert">{{ error }}</div>
        {% endif %}

        {% if message %}
        <div class="alert alert-success" role="alert">{{ message }}</div>
        {% endif %}

        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('.edit')}}" role="form">

            {{ form.hidden_tag() }}

            {{ render_field(form.firstname, class='form-control') }}
            {{ render_field(form.lastname, class='form-control') }}

            {{ render_field(form.username, class='form-control') }}
            {{ render_field(form.email, class='form-control') }}

            {{ render_field(form.bio, maxlength="160", rows="3", class='form-control') }}

            <button type="submit" class="btn btn-default">Save</button>

        </form>

    </div>

</div>
{% endblock %}

templates/user/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>User Login</h3>

    {% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endif %}

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('.login')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.username, class='form-control') }}
      {{ render_field(form.password, class='form-control') }}

      <button type="submit" class="btn btn-default">Login</button>

    </form>

  </div>

</div>
{% endblock %}

templates/user/profile.html
{% extends "base.html" %}

{% block title %}{{ user.username }} - Profile{% endblock %}

{% block header %}
<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

    <div class="col-md-3">

        <img class="img-thumbnail" src="//placehold.it/200x200" width="200" heigh="200" alt="{{ user.username }}">

        <h3>{{ user.firstname }} {{ user.lastname }} </h3>
        <h4><a href="{{ url_for('user_app.profile', username=user.username) }}" />@{{ user.username }}</a></h4>

    </div> <!-- col-md-3 -->

    <div class="col-md-9">

        <div id="friends-toolbar" class="row">

            <div class="btn-toolbar pull-right" role="toolbar" aria-label="friends-toolbar">
                <div class="btn-group" role="group" aria-label="friends-toolbar-buttons">
                    {% if edit_profile %}
                    <a href="{{ url_for('.edit') }}" role="button" class="btn btn-default">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        Edit Profile
                    </a>
                    {% else %}
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Friends
                    </button>
                    {% endif %}
                </div>
            </div>

        </div> <!-- friends-toolbar -->

        <div class="row">

            <div class="col-md-9">

                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object" src="//placehold.it/50x50" width="50" heigh="50"
                                alt="{{ user.username }}">
                        </a>
                    </div>
                    <div class="media-body">
                        <p>Luis Escobar <a href="#">@luis</a><br />
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis non massa ut ante interdum
                            sagittis. Quisque eu sapien enim. Phasellus sit amet viverra massa, sit amet rhoncus dui.
                            Nam tortor justo, finibus ut gravida et, accumsan ac sapien. Integer nec commodo libero. Nam
                            auctor vestibulum congue. Donec convallis mollis lorem, eu mattis sem luctus in. Curabitur
                            tincidunt odio sit amet nulla fringilla, vel gravida orci aliquam. Donec viverra mollis
                            tortor, a suscipit risus molestie at. Sed ut tincidunt metus. Maecenas nec dignissim velit,
                            eget placerat lectus.
                        </p>
                    </div>
                </div> <!-- media -->

                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object" src="//placehold.it/50x50" width="50" heigh="50"
                                alt="{{ user.username }}">
                        </a>
                    </div>
                    <div class="media-body">
                        <p>Luis Escobar <a href="#">@luis</a><br />
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis non massa ut ante interdum
                            sagittis. Quisque eu sapien enim. Phasellus sit amet viverra massa, sit amet rhoncus dui.
                            Nam tortor justo, finibus ut gravida et, accumsan ac sapien. Integer nec commodo libero. Nam
                            auctor vestibulum congue. Donec convallis mollis lorem, eu mattis sem luctus in. Curabitur
                            tincidunt odio sit amet nulla fringilla, vel gravida orci aliquam. Donec viverra mollis
                            tortor, a suscipit risus molestie at. Sed ut tincidunt metus. Maecenas nec dignissim velit,
                            eget placerat lectus.
                        </p>
                    </div>
                </div> <!-- media -->

            </div> <!-- col-md-9 -->

            <div class="col-md-3">

                <h4><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Friends <span
                        class="badge">4</span></h4>

                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object" src="//placehold.it/50x50" width="50" heigh="50"
                                alt="{{ user.username }}">
                        </a>
                    </div>
                    <div class="media-body">
                        <p>Luis Escobar<br />
                            <a href="#">@luis</a>
                        </p>
                    </div>
                </div> <!-- media -->

                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object" src="//placehold.it/50x50" width="50" heigh="50"
                                alt="{{ user.username }}">
                        </a>
                    </div>
                    <div class="media-body">
                        <p>Luis Escobar<br />
                            <a href="#">@luis</a>
                        </p>
                    </div>
                </div> <!-- media -->

            </div> <!-- col-md-3 -->

        </div> <!-- row -->

    </div> <!-- col-md-9 -->

</div>
{% endblock %}

templates/user/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}

<div class="row">

    <div class="col-md-offset-3 col-md-6">

        <h3>Registration</h3>

        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('.register')}}" role="form">

            {{ form.hidden_tag() }}

            {{ render_field(form.first_name, class='form-control') }}
            {{ render_field(form.last_name, class='form-control') }}

            {{ render_field(form.username, class='form-control') }}
            {{ render_field(form.email, class='form-control') }}

            {{ render_field(form.password, class='form-control') }}
            {{ render_field(form.confirm, class='form-control') }}

            <button type="submit" class="btn btn-default">Register</button>

        </form>

    </div>

</div>
{% endblock %}